import path from 'node:path';
import { promises as fs } from 'node:fs';
import { PurgeCSS } from 'purgecss';

const safelistModule = await import('../config/purge-safelist.cjs');
const safelist = safelistModule.default ?? safelistModule;

const contentGlobs = ['src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx,json}'];

const targets = [
  {
    input: 'node_modules/animate.css/animate.css',
    output: 'public/css/animate.purged.css',
  },
];

const ensureDir = async (filePath) => {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
};

const exists = async (filePath) => {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
};

for (const target of targets) {
  if (!(await exists(target.input))) {
    console.warn(`[purge-css] Skipped missing input: ${target.input}`);
    continue;
  }

  const result = await new PurgeCSS().purge({
    content: contentGlobs,
    css: [target.input],
    safelist,
    defaultExtractor: (content) => content.match(/[A-Za-z0-9-_:/]+/g) || [],
  });

  const css = result?.[0]?.css ?? '';
  await ensureDir(target.output);
  await fs.writeFile(
    target.output,
    `/* Generated by scripts/purge-css.mjs. Do not edit manually. */\n${css}\n`,
    'utf8',
  );

  console.log(`[purge-css] Wrote ${target.output}`);
}
